server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # DEMANDA
    location /api/demandas/ {
        proxy_pass http://demanda-service:5004/;
    }

    # PRODUTOS
    location /api/produtos/ {
        proxy_pass http://produtos-service:5002/;
    }

    # USUÁRIOS
    location /api/usuarios/ {
        proxy_pass http://usuarios-service:5001/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}