version: "3.7"
services:
  redpanda-teste:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda-teste
    command:
      - redpanda
      - start
      - --mode dev-container
      # Configura as duas "portas" de entrada
      - --kafka-addr internal://0.0.0.0:29092,external://0.0.0.0:9092
      # Ensina o Redpanda como ele deve se apresentar para quem perguntar
      - --advertise-kafka-addr internal://redpanda-teste:29092,external://localhost:9092
    ports:
      - "9092:9092"
      - "29092:29092"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      # O console usa a porta interna para conversar
      - KAFKA_BROKERS=redpanda-teste:29092
    ports:
      - "8080:8080"
    depends_on:
      - redpanda-teste
